.PHONY: 02-client-tools, 03-compute-resources

02-client-tools:
	cd 02-client-tools && make
03-compute-resources:
	cd 03-compute-resources && make

clean:
	#cd 02-client-tools && make clean
	cd 03-compute-resources && make clean
